version: 2
updates:
- package-ecosystem: bundler
  directory: "/docs"
  schedule:
    interval: daily
    time: '08:00'
    timezone: America/Los_Angeles
  open-pull-requests-limit: 99
  reviewers:
  - LanikSJ
  assignees:
  - LanikSJ
  labels:
  - ruby
  - dependencies
  allow:
  - dependency-type: direct
  - dependency-type: indirect
