name: 'Lock Threads'

on:
  schedule:
    - cron: '0 5 */30 * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: lock
  cancel-in-progress: true

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v4
